#' Sample \code{modelStan} output to demonstrate use of package.
#'
#' First 100 rows of posterior output generated by using \code{modelStan} function based on \code{DATASET}.
#'
#' @format A dataframe of 10 rows and 7524 columns:
#' \describe{
#'   \item{tau}{MCMC output for parameter tau based on stan script}
#'   ...
#' }
"df_of_draws"
